
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox3;

	private global::Gtk.HBox hbox4;

	private global::Gtk.Label file_chooser_proxy;

	private global::Gtk.Label lexeme_table_label;

	private global::Gtk.Label symbol_table_label;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Fixed fixed1;

	private global::Gtk.Label label1;

	private global::Gtk.Label label2;

	private global::Gtk.Button button2;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.NodeView lexeme_table;

	private global::Gtk.ScrolledWindow GtkScrolledWindow1;

	private global::Gtk.NodeView symbol_table;

	private global::Gtk.Label execute_label;

	private global::Gtk.ScrolledWindow GtkScrolledWindow2;

	private global::Gtk.TextView textview1;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.DefaultHeight = 5;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.Name = "hbox4";
		this.hbox4.Homogeneous = true;
		this.hbox4.Spacing = 1;
		// Container child hbox4.Gtk.Box+BoxChild
		this.file_chooser_proxy = new global::Gtk.Label();
		this.file_chooser_proxy.CanDefault = true;
		this.file_chooser_proxy.Name = "file_chooser_proxy";
		this.file_chooser_proxy.LabelProp = global::Mono.Unix.Catalog.GetString("File Chooser");
		this.hbox4.Add(this.file_chooser_proxy);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.file_chooser_proxy]));
		w1.Position = 0;
		w1.Expand = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.lexeme_table_label = new global::Gtk.Label();
		this.lexeme_table_label.CanDefault = true;
		this.lexeme_table_label.Name = "lexeme_table_label";
		this.lexeme_table_label.LabelProp = global::Mono.Unix.Catalog.GetString("Lexemes");
		this.hbox4.Add(this.lexeme_table_label);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.lexeme_table_label]));
		w2.Position = 1;
		// Container child hbox4.Gtk.Box+BoxChild
		this.symbol_table_label = new global::Gtk.Label();
		this.symbol_table_label.CanDefault = true;
		this.symbol_table_label.Name = "symbol_table_label";
		this.symbol_table_label.LabelProp = global::Mono.Unix.Catalog.GetString("Symbol Table");
		this.hbox4.Add(this.symbol_table_label);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.symbol_table_label]));
		w3.Position = 2;
		w3.Expand = false;
		this.vbox3.Add(this.hbox4);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox4]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Homogeneous = true;
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.HeightRequest = 250;
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Hmmm");
		this.fixed1.Add(this.label1);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label1]));
		w5.X = 21;
		w5.Y = 23;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("No errors");
		this.fixed1.Add(this.label2);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label2]));
		w6.X = 19;
		w6.Y = 108;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button2 = new global::Gtk.Button();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString("Start");
		this.fixed1.Add(this.button2);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button2]));
		w7.X = 18;
		w7.Y = 209;
		this.hbox3.Add(this.fixed1);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.fixed1]));
		w8.Position = 0;
		// Container child hbox3.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.lexeme_table = new global::Gtk.NodeView();
		this.lexeme_table.CanFocus = true;
		this.lexeme_table.Name = "lexeme_table";
		this.GtkScrolledWindow.Add(this.lexeme_table);
		this.hbox3.Add(this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.GtkScrolledWindow]));
		w10.Position = 1;
		// Container child hbox3.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.symbol_table = new global::Gtk.NodeView();
		this.symbol_table.CanFocus = true;
		this.symbol_table.Name = "symbol_table";
		this.GtkScrolledWindow1.Add(this.symbol_table);
		this.hbox3.Add(this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.GtkScrolledWindow1]));
		w12.Position = 2;
		this.vbox3.Add(this.hbox3);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox3]));
		w13.Position = 1;
		w13.Expand = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.execute_label = new global::Gtk.Label();
		this.execute_label.HeightRequest = 20;
		this.execute_label.Name = "execute_label";
		this.execute_label.LabelProp = global::Mono.Unix.Catalog.GetString("Execute\n");
		this.vbox3.Add(this.execute_label);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.execute_label]));
		w14.Position = 2;
		w14.Expand = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
		this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
		this.textview1 = new global::Gtk.TextView();
		this.textview1.HeightRequest = 200;
		this.textview1.CanFocus = true;
		this.textview1.Name = "textview1";
		this.GtkScrolledWindow2.Add(this.textview1);
		this.vbox3.Add(this.GtkScrolledWindow2);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.GtkScrolledWindow2]));
		w16.PackType = ((global::Gtk.PackType)(1));
		w16.Position = 3;
		this.Add(this.vbox3);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 643;
		this.file_chooser_proxy.HasDefault = true;
		this.lexeme_table_label.HasDefault = true;
		this.symbol_table_label.HasDefault = true;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.button2.Clicked += new global::System.EventHandler(this.OnButton2Clicked);
	}
}
